<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0k9taoi\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0k9taoi/appProdProjectContainer.php') {
    touch(__DIR__.'/Container0k9taoi.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container0k9taoi\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container0k9taoi\appProdProjectContainer([
    'container.build_hash' => '0k9taoi',
    'container.build_id' => 'd020a8fc',
    'container.build_time' => 1653771140,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0k9taoi');
